/**
 * Echarts 省份和地图文件名称的映射关系
 */
const echartsProvinceMapName = {
    浙江: 'zhejiang',
    云南: 'yunnan',
    西藏: 'xizang',
    新疆: 'xinjiang',
    香港: 'xianggang',
    天津: 'tianjin',
    台湾: 'taiwan',
    山东: 'shandong',
    陕西: 'shanxi1',
    山西: 'shanxi',
    上海: 'shanghai',
    青海: 'qinghai',
    宁夏: 'ningxia',
    内蒙古: 'neimenggu',
    辽宁: 'liaoning',
    吉林: 'jilin',
    江西: 'jiangxi',
    江苏: 'jiangsu',
    湖南: 'hunan',
    湖北: 'hubei',
    河南: 'henan',
    河北: 'hebei',
    黑龙江: 'heilongjiang',
    贵州: 'guizhou',
    广西: 'guangxi',
    广东: 'guangdong',
    甘肃: 'gansu',
    福建: 'fujian',
    重庆: 'chongqing',
    北京: 'beijing',
    澳门: 'aomen',
    安徽: 'anhui',
    海南: 'hainan',
    四川: 'sichuan',
}

export default echartsProvinceMapName;
