const echartsTheme = {
  version: 1,
  themeName: 'bi',
  theme: {
    seriesCnt: '2',
    backgroundColor: 'rgba(0,0,0,0)',
    titleColor: '#263035',
    subtitleColor: '#576272',
    textColorShow: false,
    textColor: '#333',
    markTextColor: '#ffffff',
    color: [
      '#3cc8b4',
      // '#32b0f6',
      '#0099ff',
      '#74d13d',
      '#ffcc2a',
      '#ff6d67',
      '#9667e6',
      '#4c64c8',
      '#4b5278',
      '#b9ede0',
      '#d8f8ed',
      '#7ad7ff',
      '#cceef9',
      '#b7eb8f',
      '#d9f5bd',
      '#ffe97a',
      '#f9f4c0',
      '#ffbfb8',
      '#fbd8d2',
      '#dec4ff',
      '#f1e4fc',
      '#9dafe0',
      '#dde6f8',
      '#95979e',
      '#d8dbe6'
    ],
    borderColor: '#e6ebf0',
    borderWidth: '1',
    visualMapColor: ['#bf444c', '#d88273', '#f6efa6'],
    legendTextColor: '#333333',
    kColor: '#f9434d',
    kColor0: '#47b262',
    kBorderColor: '#eb5454',
    kBorderColor0: '#11cb9e',
    kBorderWidth: 1,
    lineWidth: '2',
    symbolSize: 4,
    symbol: 'emptyCircle',
    symbolBorderWidth: '2',
    lineSmooth: false,
    graphLineWidth: 1,
    graphLineColor: '#aaaaaa',
    mapLabelColor: '#000',
    mapLabelColorE: 'rgb(100,0,0)',
    mapBorderColor: '#444',
    mapBorderColorE: '#444',
    mapBorderWidth: 0.5,
    mapBorderWidthE: 1,
    mapAreaColor: '#eee',
    mapAreaColorE: 'rgba(255,215,0,0.8)',
    axes: [
      {
        type: 'all',
        name: '通用坐标轴',
        axisLineShow: true,
        axisLineColor: '#6E7079',
        axisTickShow: true,
        axisTickColor: '#6E7079',
        axisLabelShow: true,
        axisLabelColor: '#6E7079',
        splitLineShow: true,
        splitLineColor: ['#E0E6F1'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.2)', 'rgba(210,219,238,0.2)']
      },
      {
        type: 'category',
        name: '类目坐标轴',
        axisLineShow: true,
        axisLineColor: '#e6ebf0',
        axisTickShow: true,
        axisTickColor: '#e6ebf0',
        axisLabelShow: true,
        axisLabelColor: '#858e99',
        splitLineShow: false,
        splitLineColor: ['#E0E6F1'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.2)', 'rgba(210,219,238,0.2)']
      },
      {
        type: 'value',
        name: '数值坐标轴',
        axisLineShow: false,
        axisLineColor: '#6E7079',
        axisTickShow: false,
        axisTickColor: '#6E7079',
        axisLabelShow: true,
        axisLabelColor: '#6E7079',
        splitLineShow: true,
        splitLineColor: ['#E0E6F1'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.2)', 'rgba(210,219,238,0.2)']
      },
      {
        type: 'log',
        name: '对数坐标轴',
        axisLineShow: false,
        axisLineColor: '#6E7079',
        axisTickShow: false,
        axisTickColor: '#6E7079',
        axisLabelShow: true,
        axisLabelColor: '#6E7079',
        splitLineShow: true,
        splitLineColor: ['#E0E6F1'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.2)', 'rgba(210,219,238,0.2)']
      },
      {
        type: 'time',
        name: '时间坐标轴',
        axisLineShow: true,
        axisLineColor: '#6E7079',
        axisTickShow: true,
        axisTickColor: '#6E7079',
        axisLabelShow: true,
        axisLabelColor: '#6E7079',
        splitLineShow: false,
        splitLineColor: ['#E0E6F1'],
        splitAreaShow: false,
        splitAreaColor: ['rgba(250,250,250,0.2)', 'rgba(210,219,238,0.2)']
      }
    ],
    axisSeperateSetting: true,
    toolboxColor: '#576272',
    toolboxEmphasisColor: '#576272',
    tooltipAxisColor: '#e6ebf0',
    tooltipAxisWidth: 1,
    timelineLineColor: '#dae1f5',
    timelineLineWidth: 2,
    timelineItemColor: '#a4b1d7',
    timelineItemColorE: '#ffffff',
    timelineCheckColor: '#316bf3',
    timelineCheckBorderColor: '#ffffff',
    timelineItemBorderWidth: 1,
    timelineControlColor: '#a4b1d7',
    timelineControlBorderColor: '#a4b1d7',
    timelineControlBorderWidth: 1,
    timelineLabelColor: '#a4b1d7'
  }
};

export default echartsTheme;
